# Generated by Django 2.1.7 on 2019-04-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asker', '0003_auto_20190414_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='text',
        ),
    ]
